### ISSUE TITLE
Make a few folders

### ISSUE THREAD

**Issue by dufferzafar** [hthuwal/competitive-programming#1]
Abhi toh repo mein bhasad machi hui hai :laughing: 

- `Python/*`
- `CPP/*`
- `Hacker Rank/*`

**Comment by hthuwal** [comment]
Language wise I'll do....but even idk which questions are for which coding website. Codechef, hackerearth, hackerrank, spoj, uva online judge, topcoder 😂😂

**Comment by dufferzafar** [comment]
Haan abhi language wise hi kar do. Wo hi theek hai. 

And fir jo aage kar rahe usko alag kar do.

**Comment by hthuwal** [comment]
Okay !!

**Comment by hthuwal** [comment]
Done :)
